### ISSUE TITLE
Totals = 0 in outputs 2.5, 2.6 and 2.7

### ISSUE THREAD

**Issue by JR-Farcli** [UMC-Utrecht-RWE/ConcePTION-Level2#1] opened 2022-07-11 11:53 UTC
This is not an error report of your scripts but a request for clarification how they are generated.

Revising Epichron Level 2 QC outputs, we found that for outputs 2.5, 2.6 and 2.7 anything is being picked (all totals are 0, see images attached).
I have tried to undesrtand what is needed to be picked to get results there. Is it possible that anything is showing up because these outputs are being generated by linking visit_occurrence_id, and we do not have it?
Could it be our fault placing the directories?

It would be very helpful if you can give advise on what to fix to get the numbers.
[Presentación1.pdf](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level2/files/9083655/Presentacion1.pdf)

Best,
Judit

**Comment by t-andresvaz** [comment] 2022-07-15 09:15
Hi @JR-Farcli , as you are saying that this is not a bug, I will label this activity as an improvement in our documentation - so your questions can be answered in our documents on how to run check level 2. Do you agree?

**Comment by JR-Farcli** [comment] 2022-07-15 09:27
Apart of improving documentation, to solve our problems I would need that you confirm if visit occurrence id's are used to build  OBSERVATIONS PERIODS.
Thanks again!

**Comment by t-andresvaz** [comment] 2022-07-15 09:31
Not in the pfizer scripts and also not in level3.

@JR-Farcli , please, if this answer is correct you can close this issue.

**Comment by JR-Farcli** [comment] 2022-07-15 10:33
@danielweibel can you confirm this solution is good?

**Comment by MeriPM** [comment] 2022-07-15 10:43
Dear all, IDIAP team have the same problem for the same reason. We only have values for visit_occurrence_id in VISIT_OCCURRENCE. We think that it needs to be improved because the execution of these steps take a lot of time, more than three days.

**Comment by JR-Farcli** [comment] 2022-07-19 10:49
@sluca91
In PEDIANET we have the same issue. It seems like could be a bug in the Totals calculation (eg. that the presence of NA in the column makes the total not to be calculated so maybe na.rm should be set to FALSE?).

I think Luca and PEDIANET programmers can give their scope on this.

**Comment by t-andresvaz** [comment] 2022-07-26 13:10
Please @JR-Farcli and @MeriPM could you confirm if the issue on Checklevel 2 was solved with the new[ Release 2.1](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level2/releases/tag/Version2.1) ?

**Closed** 2022-07-26 13:14 UTC
Labels: documentation

**Comment by JR-Farcli** [comment] 2022-07-26 14:01
Hi @t-andresvaz I have not had the chance to see...
@danielweibel as I see you closed, I guess you have had the occasion to confirm/see this has been solved. @MeriPM  is this your case also?

Then can I ask the DAPs to re-run L2?

**Comment by DanOV** [comment] 2022-07-27 14:06
Hi @t-andresvaz I am working on this QC for the SIDIAP database and using the last release we still have the same issues.
Thanks!
Dan
