### ISSUE TITLE
Issues 2.3 and 2.4 in SURVEY_ID

### ISSUE THREAD

**Issue by DanOV** [UMC-Utrecht-RWE/ConcePTION-Level2#6] opened 2022-07-29 08:19 UTC
Hi, 

We have obtained the following issue in reports 2.3 and 2.4:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/8267142/181716044-4f1e0570-2100-40f5-85b0-28e608357395.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/8267142/181715961-cfc5309e-1c9a-4a1c-a981-a489064654e9.png">

But we looked at our data and everything looks good so we are not really understanding why we have this <5 issues in SURVEY_ID...

What do you think?

Thanks!

Dan

**Comment by clobart** [comment] 2022-08-01 08:21
We also still found people not present in PERSONS table, even after the #2 fix. 
Can you please check that **all** tables starting with PERSONS and OBSERVATION_PERIODS are used to perform these checks? 
@relbersumcu @acidroyo-UMCU

**Comment by relbersumcu** [comment] 2022-08-01 08:47
@clobart  would it be possible to to run the level2 on the test sample and tell me which subject is missing that should be in. I really have no idea what is the issue here. Are subject not imported, are they excluded somewhere?

**Comment by clobart** [comment] 2022-08-01 09:30
@relbersumcu Yes, it's possible to run on a sample, but do you read all the table that starts with *PERSONS* or do you only read one PERSONS table when you import csv? 

I don't know to see which is the final PERSONS table that are used to check person in other CDM tables, so I can not say if you take ALL or only a part

**Comment by relbersumcu** [comment] 2022-08-01 09:49
@clobart in the previous fix I went through the code to seek for places where persons files or observation_period files where imported. There I made it so that multiple files could be imported. So as far as I can oversee the awser is YES all tables that start with PERSONS are imported. So for now there can be 2 problems, I missed a place where PERSONS files or OBSERVATION_PERIODS files are imported, OR there is a another problem. For section 2.3,and 2.4 I went again through the code but I could not see places where PERSONS or OBSERVATION_PERIODS files are imported that I missed. Since I did not wrote the code and the importing of files is not done on 1 place but repreatingly done throughout the whole script, I can imagine I missed an import. However, if this is not I am hunting a ghost. So therefore, I would be helpfull is we can provide a reporducable input that gives an unexpected result so I can debug on that. @DanOV , also in your example I would like to know more specific what result was expected based on which inputs. When I am looking to you report a a small number of issues is found. Would you expect 0 or did you find more issues? How can I be sure that that your conclusion is the correct conclusion?

**Comment by clobart** [comment] 2022-08-01 13:56
We understood the problem in our data, and it's not a bug in the level check program. 
Thanks for the support and sorry for the incovenience!

**Comment by t-andresvaz** [comment] 2022-08-01 20:09
Hi @clobart , so I will close this issue as "Won't fix". Thanks

**Closed by t-andresvaz** 2022-08-01 20:09 UTC
Labels: wontfix
